<?php
namespace App\Http\Controllers\Api\V1;
use App\Http\Controllers\Controller;use App\Models\MedicationReport;use Illuminate\Http\JsonResponse;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;
class MedicationMonitoringController extends Controller {
 public function map(Request $r):JsonResponse{$this->staff($r);$items=MedicationReport::query()->with('patient:id,full_name')->whereNotNull('latitude')->whereNotNull('longitude')->latest('server_received_at')->limit(500)->get(['id','patient_id','latitude','longitude','gps_accuracy','formatted_address','server_received_at','status']);return response()->json(['success'=>true,'data'=>$items]);}
 public function photo(Request $r,MedicationReport $report){$user=$r->user();$owned=$user->role==='pasien'&&$report->patient?->user_id===$user->id;abort_unless($owned||in_array($user->role,['admin','staff'],true),403);abort_unless(\Illuminate\Support\Facades\Storage::disk('local')->exists($report->photo_path),404);return response(\Illuminate\Support\Facades\Storage::disk('local')->get($report->photo_path),200,['Content-Type'=>'image/webp','Cache-Control'=>'private, no-store']);}
 private function staff(Request $r):void{abort_unless(in_array($r->user()->role,['admin','staff'],true),403);}
 public function index(Request $r):JsonResponse{$this->staff($r);$targetDate=$r->input('date')?:now()->toDateString();$items=MedicationReport::query()->with('patient:id,full_name,phone')->whereDate('report_date',$targetDate)->when($r->input('status'),fn($q,$s)=>$q->where('status',$s))->latest('server_received_at')->paginate(min((int)$r->input('per_page',20),100));return response()->json(['success'=>true,'data'=>$items->items(),'meta'=>['total'=>$items->total()]]);}
 public function verify(Request $r,MedicationReport $report):JsonResponse{$this->staff($r);$data=$r->validate(['status'=>['required','in:verified,rejected,follow_up'],'verification_note'=>['nullable','string','max:2000']]);if($data['status']==='rejected')abort_if(empty($data['verification_note']),422,'Catatan penolakan wajib diisi.');$report->update(['status'=>$data['status'],'verified_by'=>$r->user()->id,'verified_at'=>now(),'verification_note'=>$data['verification_note']??null]);return response()->json(['success'=>true,'message'=>'Laporan berhasil diverifikasi.','data'=>$report->fresh()]);}
 public function update(Request $r,MedicationReport $report):JsonResponse{$this->staff($r);$data=$r->validate(['medication_taken'=>['required','boolean'],'not_taken_reason'=>['nullable','string','max:2000'],'has_side_effect'=>['required','boolean'],'side_effect_category'=>['nullable','string','max:100'],'side_effect_description'=>['nullable','string','max:2000'],'status'=>['sometimes','in:submitted,verified,rejected,follow_up'],'verification_note'=>['nullable','string','max:2000']]);$report->update($data);return response()->json(['success'=>true,'message'=>'Laporan berhasil diperbarui.','data'=>$report->fresh()]);}
 public function destroy(Request $r,MedicationReport $report):JsonResponse{$this->staff($r);if($report->photo_path)\Illuminate\Support\Facades\Storage::disk('local')->delete($report->photo_path);$report->delete();return response()->json(['success'=>true,'message'=>'Laporan berhasil dihapus.'],204);}
 public function sideEffects(Request $r):JsonResponse{$this->staff($r);return response()->json(['success'=>true,'data'=>DB::table('side_effect_reports')->join('patients','patients.id','=','side_effect_reports.patient_id')->where('follow_up_status','!=','resolved')->select('side_effect_reports.*','patients.full_name')->latest('side_effect_reports.created_at')->get()]);}
 public function followUp(Request $r,int $sideEffect):JsonResponse{$this->staff($r);$data=$r->validate(['status'=>['required','in:contacted,resolved'],'resolution_note'=>['nullable','string','max:2000']]);DB::table('side_effect_reports')->where('id',$sideEffect)->update(['follow_up_status'=>$data['status'],'assigned_to'=>$r->user()->id,'resolved_at'=>$data['status']==='resolved'?now():null,'resolution_note'=>$data['resolution_note']??null,'updated_at'=>now()]);return response()->json(['success'=>true,'message'=>'Tindak lanjut diperbarui.']);}
 public function unreported(Request $r):JsonResponse{$this->staff($r);$targetDate=$r->input('date')?:now()->toDateString();$reportedIds=DB::table('medication_reports')->whereDate('report_date',$targetDate)->pluck('patient_id');$items=\App\Models\Patient::where('status','active')->whereNotIn('id',$reportedIds)->with('cadre:id,full_name')->get(['id','full_name','phone','cadre_id']);return response()->json(['success'=>true,'data'=>$items]);}
}
