<?php
namespace App\Http\Controllers\Api\V1;
use App\Http\Controllers\Controller;use Barryvdh\DomPDF\Facade\Pdf;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use PhpOffice\PhpSpreadsheet\Spreadsheet;use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
class ReportExportController extends Controller {
 private function rows(Request $r){abort_unless(in_array($r->user()->role,['admin','staff'],true),403);return DB::table('medication_reports')->join('patients','patients.id','=','medication_reports.patient_id')->when($r->input('date_from'),fn($q,$d)=>$q->whereDate('report_date','>=',$d))->when($r->input('date_to'),fn($q,$d)=>$q->whereDate('report_date','<=',$d))->select('patients.full_name','patients.nik','medication_reports.report_date','medication_reports.medication_taken','medication_reports.has_side_effect','medication_reports.status','medication_reports.server_received_at')->orderByDesc('server_received_at')->get();}
 public function csv(Request $r){$rows=$this->rows($r);return response()->streamDownload(function()use($rows){$out=fopen('php://output','w');fputcsv($out,['Pasien','NIK','Tanggal','Minum Obat','Efek Samping','Status','Waktu Server']);foreach($rows as $x)fputcsv($out,[$x->full_name,$x->nik,$x->report_date,$x->medication_taken?'Ya':'Tidak',$x->has_side_effect?'Ya':'Tidak',$x->status,$x->server_received_at]);fclose($out);},'laporan-kepatuhan.csv',['Content-Type'=>'text/csv']);}
 public function excel(Request $r){$rows=$this->rows($r);$book=new Spreadsheet();$sheet=$book->getActiveSheet();$sheet->fromArray(['Pasien','NIK','Tanggal','Minum Obat','Efek Samping','Status','Waktu Server'],null,'A1');foreach($rows as $i=>$x)$sheet->fromArray([$x->full_name,$x->nik,$x->report_date,$x->medication_taken?'Ya':'Tidak',$x->has_side_effect?'Ya':'Tidak',$x->status,$x->server_received_at],null,'A'.($i+2));return response()->streamDownload(fn()=> (new Xlsx($book))->save('php://output'),'laporan-kepatuhan.xlsx',['Content-Type'=>'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet']);}
 public function pdf(Request $r){$rows=$this->rows($r);$html='<h2>Laporan Kepatuhan Minum Obat</h2><table width="100%" border="1" cellspacing="0" cellpadding="5"><tr><th>Pasien</th><th>Tanggal</th><th>Minum</th><th>Efek Samping</th><th>Status</th></tr>';foreach($rows as $x)$html.='<tr><td>'.e($x->full_name).'</td><td>'.$x->report_date.'</td><td>'.($x->medication_taken?'Ya':'Tidak').'</td><td>'.($x->has_side_effect?'Ya':'Tidak').'</td><td>'.$x->status.'</td></tr>';$html.='</table>';return Pdf::loadHtml($html)->download('laporan-kepatuhan.pdf');}
}
