<script setup lang="ts">
import { onMounted, ref } from 'vue'
type Place={id:number;name:string;type:string;address:string;phone?:string}
const items=ref<Place[]>([]),form=ref({name:'',type:'Puskesmas',address:'',phone:''}),error=ref(''),saved=ref(''),editingId=ref<number|null>(null),saving=ref(false)
const base=import.meta.env.VITE_API_BASE_URL??'http://127.0.0.1:8010/api/v1',headers={Authorization:`Bearer ${sessionStorage.getItem('tb_token')}`,Accept:'application/json'}
const types=['Puskesmas','RSUD','RS UMUM','Lainnya']
async function load(){try{const r=await fetch(`${base}/treatment-places`,{headers}),p=await r.json();if(!r.ok)throw new Error(p.message);items.value=p.data}catch{error.value='Gagal memuat data.'}}
function reset(){form.value={name:'',type:'Puskesmas',address:'',phone:''};editingId.value=null}
function edit(item:Place){editingId.value=item.id;form.value={name:item.name,type:item.type,address:item.address,phone:item.phone??''};saved.value='';error.value='';window.scrollTo({top:0,behavior:'smooth'})}
async function submit(){saving.value=true;error.value='';saved.value='';try{const url=editingId.value?`${base}/treatment-places/${editingId.value}`:`${base}/treatment-places`;const r=await fetch(url,{method:editingId.value?'PUT':'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify(form.value)}),p=await r.json();if(!r.ok)throw new Error(p.message??'Gagal menyimpan.');saved.value=editingId.value?'Data tempat pengobatan diperbarui.':'Tempat pengobatan tersimpan.';reset();await load()}catch(e){error.value=e instanceof Error?e.message:'Gagal menyimpan.'}finally{saving.value=false}}
onMounted(load)
</script>
<template><main class="admin-page"><section class="admin-content"><header><div><p>Master data</p><h1>Tempat Pengobatan</h1><p class="page-subtitle">Kelola fasilitas rujukan dan layanan pengobatan pasien.</p></div></header><form class="panel form-grid" @submit.prevent="submit"><div class="form-title wide"><b>{{editingId?'Edit Tempat Pengobatan':'Tambah Tempat Pengobatan'}}</b><button v-if="editingId" type="button" @click="reset">Batal edit</button></div><label>Nama<input v-model="form.name" required></label><label>Tipe<select v-model="form.type" required><option v-for="type in types" :key="type" :value="type">{{type}}</option></select></label><label class="wide">Alamat<textarea v-model="form.address" required /></label><label>No. Telepon<input v-model="form.phone" type="tel" placeholder="Contoh: 6281234567890"></label><p v-if="error" class="login-error wide">{{error}}</p><p v-if="saved" class="success wide">{{saved}}</p><button class="save-button wide" :disabled="saving">{{saving?'Menyimpan…':editingId?'Simpan Perubahan':'Simpan Tempat Pengobatan'}}</button></form><section class="panel"><div class="table-heading"><div><h2>Daftar Tempat Pengobatan</h2><p>{{items.length}} fasilitas tersedia</p></div></div><div class="table-scroll"><table><thead><tr><th>Nama</th><th>Tipe</th><th>Alamat</th><th>No. Telepon</th><th>Aksi</th></tr></thead><tbody><tr v-if="!items.length"><td colspan="5" class="empty">Belum ada data.</td></tr><tr v-for="item in items" :key="item.id"><td><b>{{item.name}}</b></td><td><span class="type-badge">{{item.type}}</span></td><td>{{item.address}}</td><td>{{item.phone||'—'}}</td><td><button class="edit-button" type="button" @click="edit(item)">Edit data</button></td></tr></tbody></table></div></section></section></main></template>
<style scoped>
.page-subtitle{margin:5px 0;color:#6a8992;font-size:12px}.form-title{display:flex;justify-content:space-between;align-items:center;padding-bottom:5px;color:#173f59;font-size:15px}.form-title button{border:0;border-radius:8px;padding:8px 11px;background:#fff0ee;color:#b94137;font-weight:700;cursor:pointer}.table-heading{margin-bottom:14px}.table-heading h2{margin:0;color:#173f59;font-size:16px}.table-heading p{margin:4px 0 0;color:#6b8990;font-size:11px}.table-scroll{overflow:auto}.table-scroll table{min-width:780px}.type-badge{display:inline-block;border-radius:999px;padding:5px 9px;background:#e6f7f3;color:#087e72;font-size:11px;font-weight:700}.edit-button{border:0;border-radius:8px;padding:8px 11px;background:#0b9385;color:#fff;font-weight:700;font-size:12px;cursor:pointer}.empty{text-align:center;padding:30px!important;color:#748e96}
</style>
