<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
type Option = { id:number; name?:string; full_name?:string }
const saving=ref(false), loading=ref(true), photo=ref<File|null>(null), photoPreview=ref('')
function choosePhoto(event:Event){const input=event.target as HTMLInputElement;photo.value=input.files?.[0]||null;photoPreview.value=photo.value?URL.createObjectURL(photo.value):''}
const places=ref<Option[]>([]), cadres=ref<Option[]>([]), error=ref(''), saved=ref(''), form=ref({full_name:'',nik:'',birth_place:'',birth_date:'',gender:'L',phone:'',password:'12345678',rt:'',rw:'',full_address:'',treatment_place_id:'',cadre_id:'',treatment_start_date:'',tb_diagnosis:'',diagnosis_type:'',daily_dose_frequency:1})
const cadreQuery=ref(''); const filteredCadres=computed(()=>cadres.value.filter(c=>(c.full_name??'').toLowerCase().includes(cadreQuery.value.toLowerCase())))
const base=import.meta.env.VITE_API_BASE_URL ?? 'http://127.0.0.1:8010/api/v1'; const headers={Authorization:`Bearer ${sessionStorage.getItem('tb_token')}`,Accept:'application/json'}
onMounted(async()=>{try{const [p,c]=await Promise.all([fetch(`${base}/treatment-places`,{headers}),fetch(`${base}/cadres`,{headers})]);if(!p.ok||!c.ok)throw new Error('Gagal memuat pilihan');places.value=(await p.json()).data;cadres.value=(await c.json()).data}catch{error.value='Gagal memuat pilihan formulir. Silakan muat ulang halaman.'}finally{loading.value=false}})
async function submit(){if(saving.value||saved.value)return;saving.value=true;error.value='';saved.value='';try{const body=new FormData();Object.entries(form.value).forEach(([key,value])=>body.append(key,String(value)));body.set('treatment_place_id',String(Number(form.value.treatment_place_id)));if(form.value.cadre_id)body.set('cadre_id',String(Number(form.value.cadre_id)));if(photo.value)body.append('photo',photo.value);const r=await fetch(`${base}/patients`,{method:'POST',headers,body});const p=await r.json();if(!r.ok)throw new Error(p.message??'Gagal menyimpan pasien.');saved.value='Pasien dan akun login berhasil dibuat.'}catch(e){error.value=e instanceof Error?e.message:'Gagal menyimpan pasien.'}finally{saving.value=false}}
</script>
<template><main class="admin-page patient-create"><section class="admin-content"><header><div><p>Data Pasien / Pendaftaran</p><h1>Tambah Pasien</h1></div><a class="add-button" href="/admin/patients">← Kembali</a></header>
<div class="form-intro"><b>Pendaftaran pasien TB</b><p>Lengkapi data sesuai identitas pasien. Semua kolom wajib diisi, kecuali Kader PMO.</p></div>
<form @submit.prevent="submit" :aria-busy="saving">
<fieldset :disabled="saving || !!saved" class="patient-fields">
<section class="patient-section"><div class="section-caption"><span>01</span><div><h2>Identitas dan foto pasien</h2><p>Gunakan nama, NIK, dan foto sesuai identitas resmi.</p></div></div><div class="patient-grid"><label class="photo-field">Foto profil <small>JPG, PNG, atau WEBP maksimal 2 MB.</small><input type="file" accept="image/jpeg,image/png,image/webp" @change="choosePhoto" required><img v-if="photoPreview" :src="photoPreview" alt="Preview foto pasien"></label>
<label>Nama lengkap<input v-model="form.full_name" autocomplete="name" placeholder="Nama sesuai KTP" required></label>
<label>NIK<input v-model="form.nik" inputmode="numeric" pattern="[0-9]{16}" minlength="16" maxlength="16" placeholder="16 digit NIK" required><small>Masukkan 16 angka tanpa spasi.</small></label>
<label>Tempat lahir<input v-model="form.birth_place" placeholder="Kota / kabupaten kelahiran" required></label>
<label>Tanggal lahir<input v-model="form.birth_date" type="text" inputmode="numeric" placeholder="DD/MM/YYYY" pattern="[0-9]{2}/[0-9]{2}/[0-9]{4}" required><small>Format: DD/MM/YYYY</small></label>
<label>Jenis kelamin<select v-model="form.gender"><option value="L">Laki-laki</option><option value="P">Perempuan</option></select></label></div></section>
<section class="patient-section"><div class="section-caption"><span>02</span><div><h2>Kontak &amp; akun pasien</h2><p>Data ini digunakan pasien untuk masuk ke aplikasi.</p></div></div><div class="patient-grid"><label>Nomor HP<input v-model="form.phone" type="tel" autocomplete="tel" placeholder="Contoh: 081234567890" required><small>Gunakan nomor aktif milik pasien.</small></label><label>Password login<input v-model="form.password" type="password" autocomplete="new-password" minlength="8" required><small>Minimal 8 karakter. Sampaikan kepada pasien secara pribadi.</small></label></div></section>
<section class="patient-section"><div class="section-caption"><span>03</span><div><h2>Alamat tempat tinggal</h2><p>Alamat membantu petugas melakukan pendampingan dan kunjungan.</p></div></div><div class="patient-grid"><label>RT<input v-model="form.rt" inputmode="numeric" maxlength="3" placeholder="Contoh: 001" required></label><label>RW<input v-model="form.rw" inputmode="numeric" maxlength="3" placeholder="Contoh: 005" required></label><label class="full-row">Alamat lengkap<textarea v-model="form.full_address" autocomplete="street-address" placeholder="Nama jalan, nomor rumah, kelurahan, kecamatan, dan kota / kabupaten" required /></label></div></section>
<section class="patient-section"><div class="section-caption"><span>04</span><div><h2>Pengobatan &amp; pendamping</h2><p>Tentukan fasilitas pelayanan, diagnosis, dan rencana pendampingan pasien.</p></div></div><p v-if="loading" role="status">Memuat pilihan tempat pengobatan dan kader…</p><div class="patient-grid"><label>Tempat pengobatan<select v-model="form.treatment_place_id" :disabled="loading" required><option value="">Pilih tempat pengobatan</option><option v-for="p in places" :key="p.id" :value="p.id">{{p.name}}</option></select><small v-if="!loading && !places.length">Belum ada pilihan. Tambahkan tempat pengobatan melalui menu sidebar.</small></label><label>Kader PMO <em>Wajib dipilih</em><input v-model="cadreQuery" type="search" placeholder="Cari nama kader…" :disabled="loading"><select v-model="form.cadre_id" :disabled="loading" required><option value="">Pilih kader PMO</option><option v-for="c in filteredCadres" :key="c.id" :value="c.id">{{c.full_name}}</option></select><small>Pendamping atau pengawas menelan obat pasien.</small></label><label>Diagnosis TBC<select v-model="form.tb_diagnosis" required><option value="">Pilih diagnosis TBC</option><option value="TB Paru">TB Paru</option><option value="TB Ekstraparu">TB Ekstraparu</option></select></label><label>Tipe diagnosis<select v-model="form.diagnosis_type" required><option value="">Pilih tipe diagnosis</option><option value="Bakteriologis">Bakteriologis</option><option value="Klinis">Klinis</option></select></label><label>Tanggal mulai pengobatan<input v-model="form.treatment_start_date" type="date" required></label><label>Frekuensi minum obat<select v-model.number="form.daily_dose_frequency"><option :value="1">1 kali sehari</option><option :value="2">2 kali sehari</option><option :value="3">3 kali sehari</option></select><small>Isi sesuai rencana pengobatan dari petugas kesehatan.</small></label></div></section>
</fieldset><p v-if="error" class="error" role="alert">{{error}}</p><p v-if="saved" class="success" role="status">{{saved}} <a href="/admin/patients">Lihat daftar pasien →</a></p><div class="patient-actions"><p>Periksa kembali identitas dan nomor HP sebelum menyimpan.</p><button class="save-button" :disabled="saving || loading || !!saved || !places.length">{{saving?'Menyimpan…':saved?'Pasien tersimpan':'Simpan Pasien'}}</button></div></form></section></main></template>
<style scoped>
.patient-create .admin-content{max-width:1100px;margin:0 auto}.form-intro{padding:16px 20px;background:linear-gradient(115deg,#e0f6f1,#edfaff);border:1px solid #cce9e2;border-radius:12px;margin:22px 0 18px}.form-intro b{color:#087e78}.form-intro p{font-size:12px;color:#5f808b;margin:5px 0}.patient-fields{display:block;padding:0;margin:0;border:0;min-width:0}.patient-section{padding:24px;background:#fff;border:1px solid #e1edeb;border-radius:14px;margin-bottom:18px;box-shadow:0 6px 18px #28766b08}.section-caption{display:flex;gap:12px;align-items:flex-start;border-bottom:1px solid #edf2f1;padding-bottom:16px;margin-bottom:20px}.section-caption>span{display:grid;place-items:center;width:34px;height:34px;border-radius:10px;background:#e0f5ee;color:#098477;font-weight:bold;flex-shrink:0}.section-caption h2{font-size:16px;margin:0}.section-caption p{font-size:12px;color:#708b92;margin:4px 0 0}.patient-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px 24px;align-items:start}.patient-grid label{display:block;font-size:13px;font-weight:600;min-width:0}.patient-grid input,.patient-grid select,.patient-grid textarea{display:block;width:100%;min-width:0;border:1px solid #cddfdf;border-radius:9px;padding:11px 12px;margin-top:8px;font:400 14px Arial;color:#214a58;background:#fcfefe;min-height:44px}.patient-grid textarea{min-height:100px;resize:vertical}.patient-grid small{display:block;font-size:11px;font-weight:400;color:#70898e;line-height:1.5;margin-top:6px}.patient-grid em{font-size:10px;font-style:normal;color:#718d91;background:#eff5f4;border-radius:6px;padding:3px 6px;margin-left:6px}.patient-grid input:focus,.patient-grid select:focus,.patient-grid textarea:focus{outline:2px solid #a5e5da;border-color:#1a9b8d;outline-offset:1px}.full-row{grid-column:1/-1}.patient-actions{display:flex;justify-content:space-between;align-items:center;gap:16px;background:#fff;padding:18px 20px;border:1px solid #dfedeb;border-radius:12px}.patient-actions p{margin:0;color:#70898e;font-size:12px}.patient-actions button{padding:13px 26px;flex-shrink:0;cursor:pointer}.patient-actions button:disabled{opacity:.6;cursor:default}@media(max-width:700px){.patient-grid{grid-template-columns:minmax(0,1fr)}.patient-section{padding:18px}.patient-actions{flex-direction:column;align-items:stretch}.patient-actions button{width:100%}}
</style><style scoped>
.photo-field{grid-column:1/-1}.photo-field input{padding:10px}.photo-field img{display:block;width:120px;height:140px;object-fit:cover;border-radius:12px;margin-top:10px;border:2px solid #bde2d8}
</style>
