<script setup lang="ts">
import { onMounted, ref } from 'vue'
import PatientPicker from './PatientPicker.vue'
type Option={id:number;name?:string}
const saving=ref(false),places=ref<Option[]>([]),error=ref(''),saved=ref(''),form=ref({patient_id:'',treatment_place_id:'',control_date:'',start_time:'',purpose:'',notes:''})
const base='/api/v1',headers={Authorization:`Bearer ${sessionStorage.getItem('tb_token')}`,Accept:'application/json'}
onMounted(async()=>{try{const r=await fetch(`${base}/treatment-places`,{headers});const p=await r.json();if(!r.ok)throw new Error(p.message);places.value=p.data}catch{error.value='Gagal memuat tempat pengobatan.'}})
async function submit(){if(saving.value||!form.value.patient_id)return;saving.value=true;error.value='';try{const r=await fetch(`${base}/control-schedules`,{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({...form.value,patient_id:Number(form.value.patient_id),treatment_place_id:Number(form.value.treatment_place_id)})});const p=await r.json();if(!r.ok)throw new Error(p.message||'Gagal membuat jadwal.');location.href='/admin/schedules'}catch(e){error.value=e instanceof Error?e.message:'Gagal membuat jadwal.'}finally{saving.value=false}}
</script>
<template><main class="admin-page schedule-create"><section class="admin-content"><header><div><p>Monitoring pasien / Jadwal Kontrol</p><h1>Buat Jadwal Kontrol</h1><p class="page-subtitle">Buat jadwal kedatangan dan siapkan kebutuhan kunjungan pasien.</p></div><a class="add-button" href="/admin/schedules">← Kembali ke Jadwal Kontrol</a></header><form class="schedule-form" @submit.prevent="submit"><section class="schedule-section"><div class="section-head"><b>01</b><div><h2>Pilih pasien</h2><p>Cari dan cocokkan identitas pasien sebelum membuat jadwal.</p></div></div><PatientPicker @select="patient => { form.patient_id=patient?String(patient.id):''; if(patient) form.treatment_place_id=String(patient.treatment_place_id) }" /></section><section class="schedule-section"><div class="section-head"><b>02</b><div><h2>Waktu dan tempat kunjungan</h2><p>Isi kapan dan di mana pasien akan datang untuk kontrol.</p></div></div><div class="form-grid"><label>Tempat Pengobatan<select v-model="form.treatment_place_id" required><option value="">Pilih tempat</option><option v-for="p in places" :key="p.id" :value="p.id">{{p.name}}</option></select><small>Otomatis mengikuti fasilitas pasien jika tersedia.</small></label><label>Tanggal Kontrol<input v-model="form.control_date" type="date" required><small>Pilih tanggal kunjungan pasien.</small></label><label>Jam Datang<input v-model="form.start_time" type="time" required><small>Jam pasien diperkirakan tiba.</small></label></div></section><section class="schedule-section"><div class="section-head"><b>03</b><div><h2>Tujuan dan catatan</h2><p>Tambahkan informasi untuk membantu petugas menyiapkan kunjungan.</p></div></div><div class="form-grid"><label class="wide">Tujuan Kontrol<input v-model="form.purpose" placeholder="Contoh: pemeriksaan lanjutan"></label><label class="wide">Catatan Petugas<textarea v-model="form.notes" placeholder="Pengingat atau catatan khusus kunjungan"/><small>Opsional dan hanya dilihat petugas.</small></label></div></section><p v-if="error" class="error">{{error}}</p><p v-if="saved" class="success">{{saved}}</p><div class="schedule-actions"><p>Periksa kembali pasien, tanggal, dan jam datang.</p><button class="save-button" :disabled="saving || !form.patient_id">{{saving?'Menyimpan…':'Simpan Jadwal Kontrol'}}</button></div></form></section></main></template>
<style scoped>
.schedule-create .admin-content{max-width:1120px;margin:auto}.schedule-create header{align-items:flex-start}.page-subtitle{font-size:12px;color:#698496;margin:5px 0}.schedule-form{background:none;border:0;box-shadow:none;padding:0}.schedule-section{background:#fff;border:1px solid #dfedeb;border-radius:14px;padding:24px;margin-bottom:16px;box-shadow:0 8px 22px #28766b0b}.section-head{display:flex;gap:12px;border-bottom:1px solid #edf3f1;padding-bottom:15px;margin-bottom:20px}.section-head>b{display:grid;place-items:center;width:34px;height:34px;background:#e1f5ee;border-radius:10px;color:#087e78}.section-head h2{font-size:16px;margin:0}.section-head p{font-size:12px;color:#718b92;margin:4px 0}.schedule-section label{display:block;font-size:13px;font-weight:600}.schedule-section input,.schedule-section select,.schedule-section textarea{display:block;width:100%;margin-top:8px;padding:11px 12px;border:1px solid #cddfdf;border-radius:9px;background:#fcfefe;font:14px Arial;min-height:44px}.schedule-section textarea{min-height:100px;resize:vertical}.schedule-section small{display:block;margin-top:6px;color:#718b92;font-size:11px;font-weight:normal}.schedule-actions{display:flex;justify-content:space-between;align-items:center;gap:16px;background:#fff;padding:18px 20px;border:1px solid #dfedeb;border-radius:12px}.schedule-actions p{margin:0;color:#718b92;font-size:12px}.schedule-actions button{padding:13px 24px;cursor:pointer}.schedule-actions button:disabled{opacity:.55}@media(max-width:700px){.schedule-section{padding:18px}.schedule-section .form-grid{grid-template-columns:1fr}.schedule-actions{flex-direction:column;align-items:stretch}.schedule-actions button{width:100%}}
</style>
