<script setup lang="ts">
import { onMounted, ref } from 'vue'
type User={id:number;name:string;username?:string;email?:string;phone?:string;role:string;is_active:boolean}
const items=ref<User[]>([]),error=ref(''),showForm=ref(false),editingId=ref<number|null>(null),form=ref({name:'',username:'',email:'',phone:'',password:'',role:'staff'});const base=import.meta.env.VITE_API_BASE_URL??'http://127.0.0.1:8010/api/v1';const headers={Authorization:`Bearer ${sessionStorage.getItem('tb_token')}`,Accept:'application/json'}
async function load(){try{const r=await fetch(`${base}/users`,{headers});const p=await r.json();if(!r.ok)throw new Error(p.message);items.value=p.data}catch(e){error.value=e instanceof Error?e.message:'Gagal memuat pengguna.'}}onMounted(load)
async function editUser(item:User){editingId.value=item.id;form.value={name:item.name,username:item.username||'',email:item.email||'',phone:item.phone||'',password:'',role:item.role};showForm.value=true}
async function resetPassword(item:User){if(!confirm('Reset password menjadi 12345678?'))return;await fetch(`${base}/users/${item.id}`,{method:'PUT',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({password:'12345678'})});await load()}
async function submit(){error.value='';try{const r=await fetch(`${base}/users${editingId.value?'/'+editingId.value:''}`,{method:editingId.value?'PUT':'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify(form.value)});const p=await r.json();if(!r.ok)throw new Error(p.message??'Gagal menyimpan pengguna.');form.value={name:'',username:'',email:'',phone:'',password:'',role:'staff'};editingId.value=null;showForm.value=false;await load()}catch(e){error.value=e instanceof Error?e.message:'Gagal menyimpan pengguna.'}}
</script>
<template><main class="admin-page"><section class="admin-content"><header><div><p>Manajemen akses</p><h1>User Admin &amp; Staff</h1></div><button type="button" class="add-button" @click="showForm=!showForm">Tambah Data</button></header><form v-if="showForm" class="panel form-grid user-form-modal" @submit.prevent="submit"><button type="button" class="modal-close" @click="showForm=false;editingId=null">×</button><label>Nama<input v-model="form.name" required></label><label>Username<input v-model="form.username" required></label><label>Email<input v-model="form.email" type="email"></label><label>No. HP<input v-model="form.phone"></label><label>Password<input v-model="form.password" type="password" minlength="8" :required="!editingId"></label><label>Peran<select v-model="form.role"><option value="staff">Staff</option><option value="admin">Admin</option></select></label><p v-if="error" class="login-error wide">{{error}}</p><button class="save-button wide">{{editingId?'Simpan Perubahan':'Tambah Pengguna'}}</button></form><section class="panel"><table><thead><tr><th>Nama</th><th>Username</th><th>Email</th><th>Peran</th><th>Status</th><th>Aksi</th></tr></thead><tbody><tr v-for="item in items" :key="item.id"><td>{{item.name}}</td><td>{{item.username??'-'}}</td><td>{{item.email??'-'}}</td><td>{{item.role}}</td><td>{{item.is_active?'Aktif':'Nonaktif'}}</td><td><button type="button" @click="editUser(item)">Edit</button> <button type="button" @click="resetPassword(item)">Reset password</button></td></tr></tbody></table></section></section></main></template>
<style scoped>.user-form-modal{position:relative;position:fixed;z-index:80;top:50%;left:50%;transform:translate(-50%,-50%);width:min(900px,calc(100% - 40px));max-height:90vh;overflow:auto;box-shadow:0 24px 70px #163a5440} .modal-close{position:absolute;right:16px;top:14px;width:34px;height:34px;border:0;background:#fff0ef;color:#b33b36;border-radius:50%;font-size:22px;line-height:1;cursor:pointer;font-weight:bold}.user-form-modal .save-button{font-size:14px} .admin-content>header>.add-button{display:inline-flex;align-items:center;justify-content:center;min-width:150px;min-height:42px;color:#fff!important;background:#087e72!important;font-size:13px!important;font-weight:700!important;white-space:nowrap}</style>
