<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
type Option={id:number;full_name?:string;name?:string}
const patients=ref<Option[]>([]),periods=ref<string[]>([]),error=ref(''),saved=ref(''),form=ref({patient_id:'',dose:'1',frequency_per_day:1,start_date:''})
const base=import.meta.env.VITE_API_BASE_URL??'http://127.0.0.1:8010/api/v1', headers={Authorization:`Bearer ${sessionStorage.getItem('tb_token')}`,Accept:'application/json'}
const requiresPeriods=computed(()=>form.value.frequency_per_day>1)
onMounted(async()=>{try{const r=await fetch(`${base}/patients`,{headers});const p=await r.json();if(!r.ok)throw new Error(p.message);patients.value=p.data}catch{error.value='Gagal memuat data pilihan.'}})
function toggle(period:string){periods.value=periods.value.includes(period)?periods.value.filter(x=>x!==period):[...periods.value,period]}
async function submit(){error.value='';saved.value='';if(requiresPeriods.value&&periods.value.length!==form.value.frequency_per_day){error.value='Jumlah slot harus sama dengan frekuensi per hari.';return}try{const body={dose:form.value.dose,frequency_per_day:form.value.frequency_per_day,start_date:form.value.start_date,...(requiresPeriods.value?{periods:periods.value}:{})};const r=await fetch(`${base}/patients/${form.value.patient_id}/medication-plan`,{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify(body)});const p=await r.json();if(!r.ok)throw new Error(p.message??'Gagal menyimpan rencana obat.');saved.value='Rencana minum obat berhasil disimpan.'}catch(e){error.value=e instanceof Error?e.message:'Gagal menyimpan rencana obat.'}}
</script>
<template><main class="admin-page"><section class="admin-content"><header><div><p>Pengaturan pasien</p><h1>Rencana Minum Obat</h1></div></header><form class="panel form-grid" @submit.prevent="submit"><label>Pasien<select v-model="form.patient_id" required><option value="">Pilih pasien</option><option v-for="p in patients" :key="p.id" :value="p.id">{{p.full_name}}</option></select></label><label>Dosis<input v-model="form.dose" required></label><label>Tanggal Mulai<input v-model="form.start_date" type="date" required></label><label>Frekuensi<select v-model.number="form.frequency_per_day" @change="periods=[]"><option :value="1">1 kali sehari</option><option :value="2">2 kali sehari</option><option :value="3">3 kali sehari</option></select></label><div v-if="requiresPeriods" class="wide"><b>Pilih waktu minum</b><div class="periods"><button v-for="p in ['Pagi','Siang','Malam']" :key="p" type="button" :class="{chosen:periods.includes(p)}" @click="toggle(p)">{{p}}</button></div><small>Pagi 07:00 · Siang 13:00 · Malam 19:00</small></div><p v-else class="success wide">Sekali sehari tidak memerlukan jam minum.</p><p v-if="error" class="login-error wide">{{error}}</p><p v-if="saved" class="success wide">{{saved}}</p><button class="save-button wide">Simpan Rencana Obat</button></form></section></main></template>
