<script setup lang="ts">
import { onMounted, ref } from 'vue'
type Patient={id:number;full_name:string;medical_record_number?:string;nik:string;phone:string;birth_date?:string;gender?:string;rt?:string;rw?:string;full_address?:string;status:string;photo_path?:string|null;cadre?:{full_name:string;phone?:string}}
type Control={id:number;control_date:string;start_time:string;purpose?:string;status:string;treatment_place:string;attended_at?:string}
type Medication={id:number;report_date:string;scheduled_time?:string;medication_taken:boolean;not_taken_reason?:string;has_side_effect:boolean;side_effect_category?:string;status:string}
const id=Number(location.pathname.match(/\/admin\/patients\/(\d+)\/history/)?.[1]),base=import.meta.env.VITE_API_BASE_URL??'http://127.0.0.1:8010/api/v1',headers={Authorization:`Bearer ${sessionStorage.getItem('tb_token')}`,Accept:'application/json'}
const patient=ref<Patient|null>(null),controls=ref<Control[]>([]),medications=ref<Medication[]>([]),loading=ref(true),error=ref('')
const photo=(value:Patient)=>value.photo_path?`/media/profile/${value.photo_path}`:'/icons/icon-512.png'
const date=(value?:string)=>{if(!value)return '—';const [y,m,d]=value.slice(0,10).split('-');return y&&m&&d?`${d}/${m}/${y}`:value}
const controlLabel=(status:string)=>({scheduled:'Terjadwal',confirmed:'Terjadwal',attended:'Datang kontrol',missed:'Tidak datang',rescheduled:'Ganti tanggal',cancelled:'Dibatalkan'}[status]??status)
async function load(){try{const r=await fetch(`${base}/patients/${id}/history`,{headers}),p=await r.json();if(!r.ok)throw new Error(p.message??'Gagal memuat riwayat pasien.');patient.value=p.data.patient;controls.value=p.data.controls;medications.value=p.data.medications}catch(e){error.value=e instanceof Error?e.message:'Gagal memuat riwayat pasien.'}finally{loading.value=false}}
onMounted(load)
</script>
<template><main class="admin-page"><section class="admin-content"><header><div><p>Data pasien / Riwayat</p><h1>Riwayat Pasien</h1><p class="page-subtitle">Rekam kontrol dan kepatuhan minum obat pasien.</p></div><a class="add-button" href="/admin/schedules">← Kembali ke Jadwal Kontrol</a></header><p v-if="loading">Memuat riwayat pasien…</p><p v-else-if="error" class="login-error">{{error}}</p><template v-else-if="patient"><section class="history-hero"><img :src="photo(patient)" alt="Foto pasien"><div><small>Profil pasien</small><h2>{{patient.full_name}}</h2><p>{{patient.medical_record_number||'No. RM belum tersedia'}} · {{patient.status}}</p></div><div class="hero-contact"><b>{{patient.phone}}</b><span>NIK {{patient.nik}}</span></div></section><section class="identity-grid"><article><b>Identitas</b><span>{{patient.gender==='L'?'Laki-laki':'Perempuan'}} · Lahir {{date(patient.birth_date)}}</span></article><article><b>Wilayah</b><span>RT {{patient.rt||'—'}} / RW {{patient.rw||'—'}}</span></article><article><b>Kader PMO</b><span>{{patient.cadre?.full_name||'Belum ditetapkan'}}</span></article><article><b>Alamat</b><span>{{patient.full_address||'Belum tersedia'}}</span></article></section><section class="history-grid"><article class="panel"><div class="section-heading"><div><h2>Riwayat kontrol</h2><p>{{controls.length}} jadwal tercatat</p></div></div><div v-if="controls.length" class="timeline"><div v-for="control in controls" :key="control.id" class="timeline-item"><b>{{date(control.control_date)}}</b><span>{{control.start_time?.slice(0,5)}} · {{control.treatment_place}}</span><small>{{control.purpose||'Kontrol rutin'}}</small><em>{{controlLabel(control.status)}}</em></div></div><p v-else class="empty-state">Belum ada riwayat kontrol.</p></article><article class="panel"><div class="section-heading"><div><h2>Riwayat minum obat</h2><p>{{medications.length}} laporan tercatat</p></div></div><div v-if="medications.length" class="timeline"><div v-for="report in medications" :key="report.id" class="timeline-item medicine"><b>{{date(report.report_date)}}</b><span>{{report.scheduled_time?.slice(0,5)||'—'}} · {{report.medication_taken?'Sudah minum':'Belum minum'}}</span><small v-if="report.has_side_effect">Efek samping: {{report.side_effect_category||'Dilaporkan'}}</small><small v-else-if="report.not_taken_reason">{{report.not_taken_reason}}</small><em :class="report.medication_taken?'taken':'missed'">{{report.medication_taken?'Sudah minum':'Belum minum'}}</em></div></div><p v-else class="empty-state">Belum ada laporan minum obat.</p></article></section></template></section></main></template>
<style scoped>
.page-subtitle{margin:5px 0 0;color:#6a8992;font-size:12px}.history-hero{display:flex;align-items:center;gap:17px;padding:25px;border-radius:20px;background:radial-gradient(circle at 90% 20%,#b9f0e7,transparent 34%),linear-gradient(120deg,#e1faf6,#eefaff);box-shadow:0 12px 26px -18px #146d8660}.history-hero img{width:80px;height:80px;border:3px solid #fff;border-radius:22px;object-fit:cover;box-shadow:0 8px 20px #147b7240}.history-hero small{color:#078579;font-size:11px;font-weight:700;text-transform:uppercase}.history-hero h2{margin:5px 0;color:#183f59}.history-hero p{margin:0;color:#587781;font-size:12px}.hero-contact{margin-left:auto;text-align:right}.hero-contact b,.hero-contact span{display:block}.hero-contact b{color:#087e72;font-size:15px}.hero-contact span{margin-top:5px;color:#66858c;font-size:11px}.identity-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:18px 0}.identity-grid article{padding:15px;border:1px solid #dcefeb;border-radius:13px;background:#fff}.identity-grid b,.identity-grid span{display:block}.identity-grid b{color:#173f59;font-size:12px}.identity-grid span{margin-top:7px;color:#66858c;font-size:11px;line-height:1.5}.history-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.section-heading h2{margin:0;color:#173f59;font-size:16px}.section-heading p{margin:4px 0 0;color:#6b8990;font-size:11px}.timeline{margin-top:18px}.timeline-item{position:relative;padding:0 0 17px 19px;border-left:2px solid #ccebe4}.timeline-item:before{content:'';position:absolute;left:-6px;top:3px;width:10px;height:10px;border-radius:50%;background:#0b9385}.timeline-item:last-child{border-color:transparent}.timeline-item b,.timeline-item span,.timeline-item small{display:block}.timeline-item b{color:#19455e;font-size:12px}.timeline-item span{margin-top:4px;color:#526f7d;font-size:12px}.timeline-item small{margin-top:3px;color:#80969c;font-size:10px}.timeline-item em{display:inline-block;margin-top:6px;padding:4px 7px;border-radius:999px;background:#e6f7f3;color:#087e72;font-size:10px;font-style:normal;font-weight:700}.timeline-item em.missed{background:#fff0ee;color:#b94137}.empty-state{padding:26px 0 8px;color:#748e96;font-size:12px}@media(max-width:900px){.identity-grid{grid-template-columns:repeat(2,1fr)}.history-grid{grid-template-columns:1fr}}@media(max-width:600px){.history-hero{align-items:flex-start}.history-hero img{width:60px;height:60px}.history-hero h2{font-size:18px}.hero-contact{margin:64px 0 0 -76px;text-align:left}.identity-grid{grid-template-columns:1fr}}
</style>
