<script setup lang="ts">
import { onMounted, ref } from 'vue'
import AdminIcon from './AdminIcon.vue'
type Data={total_active_patients:number;taken_today:number;not_taken_today:number;unreported_today:number;side_effects_today:number;controls_today:number;history:{date:string;percent:number}[];recent_reports:{id:number;patient:{full_name:string};medication_taken:boolean;status:string;server_received_at:string;formatted_address:string|null}[];schedules:{id:number;full_name:string;start_time:string;status:string}[]}
const data=ref<Data|null>(null),error=ref('')
const user=JSON.parse(sessionStorage.getItem('tb_user')||'{}')
const formatTime=(value?:string|null)=>{if(!value)return '';const d=new Date(value);return Number.isNaN(d.getTime())?value:d.toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'})}
onMounted(async()=>{try{const r=await fetch('/api/v1/dashboard/summary',{headers:{Authorization:'Bearer '+sessionStorage.getItem('tb_token'),Accept:'application/json'}});const p=await r.json();if(!r.ok)throw new Error(p.message);data.value=p.data}catch(e){error.value=e instanceof Error?e.message:'Gagal memuat data'}})
</script>
<style scoped>
.overview-welcome { position:relative; isolation:isolate; height:190px; overflow:visible; margin:32px 0 28px; padding:28px 36px; border:1px solid #ffffff; border-radius:22px; background:radial-gradient(ellipse at 68% 15%,#ffffffd9,transparent 45%),linear-gradient(115deg,#dff8ff,#e9fbf5 60%,#bcece1); box-shadow:0 16px 30px -12px #167f8050,0 3px 6px #197d7910,inset 0 1px 0 white; }
.overview-welcome::before,.overview-welcome::after { content:''; position:absolute; pointer-events:none; z-index:-1; }
.overview-welcome::before { inset:0; border-radius:inherit; background:url('/illustrations/banner-leaves.svg') right bottom / 370px 185px no-repeat; opacity:.75; }
.overview-welcome::after { width:110px; height:110px; right:37%; top:12px; border:1px solid #ffffffbf; border-radius:50%; box-shadow:0 0 0 18px #ffffff26,0 0 0 40px #ffffff12; }
.overview-welcome>div { max-width:55%; z-index:1; }
.overview-welcome>b { z-index:1; font-size:22px; line-height:1.5; }
.overview-welcome img { position:relative; width:300px; height:220px; object-fit:contain; object-position:center bottom; align-self:flex-end; margin:0 -4px -28px 0; flex-shrink:0; filter:drop-shadow(0 9px 6px #18695425); }
.overview-metrics article,.overview-grid .card { box-shadow:0 9px 22px -12px #237a8250,0 2px 4px #286b7410; border-color:#ffffff; }
@media (max-width:1000px) { .overview-welcome { padding:24px; height:180px; } .overview-welcome img { width:240px;height:200px;margin-bottom:-24px; } .overview-welcome>div { max-width:60%; } }
@media (max-width:700px) { .overview-welcome { margin-top:20px;padding:20px;height:auto;min-height:170px;gap:8px; } .overview-welcome>div { max-width:none;flex:1;min-width:0; } .overview-welcome img { width:135px;height:155px;margin:0 -12px -20px 0; } .overview-welcome::before { background-size:230px 140px; } .overview-welcome h2 { font-size:16px; } }
</style>
<template><main class="overview"><section class="overview-welcome"><div><h2>Selamat datang, {{user.name}}!</h2><p>Pantau perkembangan pengobatan pasien TB di wilayah kerja Anda.</p></div><b>Bersama Kita<br>Akhiri TB ♡</b><img src="/illustrations/welcome-team.png" alt="Tenaga kesehatan bersama masyarakat"/></section><p v-if="error" class="error" role="alert">{{error}}</p><p v-else-if="!data" role="status">Memuat data dashboard…</p><template v-if="data">
<section class="overview-metrics"><article v-for="(item,i) in [{label:'Total Pasien Aktif',value:data.total_active_patients,icon:'users'},{label:'Kepatuhan Minum Obat',value:(data.total_active_patients?Math.round(data.taken_today/data.total_active_patients*100):0)+'%',icon:'pill'},{label:'Belum Lapor',value:data.unreported_today,icon:'alert'},{label:'Laporan Efek Samping',value:data.side_effects_today,icon:'chart'},{label:'Jadwal Kontrol',value:data.controls_today,icon:'calendar'}]" :key="item.label" :class="'metric-tone-'+i"><span><AdminIcon :name="item.icon"/></span><div><small>{{item.label}}</small><strong>{{item.value}}</strong><p>Data hari ini</p></div></article></section>
<div class="overview-grid"><section class="overview-chart card"><h3><AdminIcon name="chart"/>Grafik Kepatuhan Minum Obat <small>7 hari terakhir</small></h3><svg viewBox="0 0 370 195" role="img" aria-label="Persentase laporan minum obat pasien aktif tujuh hari terakhir"><g v-for="n in [0,20,40,60,80,100]" :key="n"><path :d="'M35 '+(165-n*1.4)+'H345'" stroke="#e4eeee"/><text x="0" :y="169-n*1.4" font-size="9" fill="#718899">{{n}}%</text></g><polyline :points="data.history.map((p,i)=>(35+i*50)+','+(165-p.percent*1.4)).join(' ')" fill="none" stroke="#0bab89" stroke-width="3"/><g v-for="(day,i) in data.history" :key="day.date"><circle :cx="35+i*50" :cy="165-day.percent*1.4" r="3" fill="#0bab89"/><text :x="35+i*50" y="188" text-anchor="middle" font-size="9" fill="#718899">{{new Date(day.date).toLocaleDateString('id-ID',{day:'numeric',month:'short'})}}</text></g></svg></section>
<section class="overview-status card"><h3><AdminIcon name="chart"/>Status Minum Obat Hari Ini</h3><div class="status-content"><div class="live-donut" :style="{background:data.total_active_patients?'conic-gradient(#0eae89 0 '+(data.taken_today/data.total_active_patients*100)+'%, #f4c437 0)':'#e3eeed'}"><div><strong>{{data.total_active_patients}}</strong><small>Pasien aktif</small></div></div><p>Sudah minum <b>{{data.taken_today}}</b><br>Belum minum <b>{{data.not_taken_today}}</b><br>Belum lapor <b>{{data.unreported_today}}</b></p></div></section>
<section class="overview-schedule card"><h3><AdminIcon name="calendar"/>Jadwal Kontrol Hari Ini</h3><a href="/admin/schedules?tab=kontrol">Kelola jadwal →</a><p v-if="!data.schedules.length" class="data-message">Belum ada jadwal kontrol hari ini.</p><div v-for="row in data.schedules" :key="row.id" class="actual-row"><time>{{row.start_time.slice(0,5)}}</time><b>{{row.full_name}}</b><small>{{row.status}}</small></div></section>
<section class="overview-location card"><h3><AdminIcon name="home"/>Pemantauan Pasien</h3><div class="location-empty"><AdminIcon name="chart"/><p>Lihat status laporan minum obat seluruh pasien hari ini.</p><a href="/admin/monitoring">Buka tabel monitoring →</a></div></section>
<section class="overview-reports card"><h3><AdminIcon name="chart"/>Laporan Terbaru Pasien</h3><div class="table-scroll"><table><thead><tr><th>Nama Pasien</th><th>Status Minum Obat</th><th>Waktu Lapor</th><th>Lokasi (GPS)</th><th>Verifikasi</th></tr></thead><tbody><tr v-for="row in data.recent_reports" :key="row.id"><td>{{row.patient.full_name}}</td><td>{{row.medication_taken?'Sudah minum':'Belum minum'}}</td><td>{{formatTime(row.server_received_at)}}</td><td>{{row.formatted_address||'Belum tersedia'}}</td><td>{{row.status}}</td></tr><tr v-if="!data.recent_reports.length"><td colspan="5" class="data-message">Belum ada laporan minum obat hari ini.</td></tr></tbody></table></div></section>
<section class="overview-notices card"><h3><AdminIcon name="alert"/>Perlu Perhatian Hari Ini</h3><div class="attention-list"><a href="/admin/patients"><AdminIcon name="users"/><span><b>{{data.unreported_today}} pasien belum mengirim laporan</b><small>Buka data pasien untuk tindak lanjut</small></span><em>Data pasien →</em></a><a href="/admin/monitoring"><AdminIcon name="alert"/><span><b>{{data.side_effects_today}} laporan efek samping</b><small>{{data.side_effects_today?'Ada laporan efek samping hari ini.':'Belum ada laporan efek samping hari ini.'}}</small></span><em>Monitoring →</em></a><a href="/admin/schedules"><AdminIcon name="calendar"/><span><b>{{data.controls_today}} jadwal kontrol hari ini</b><small>Lihat daftar jadwal kedatangan pasien</small></span><em>Jadwal kontrol →</em></a></div></section>
</div></template></main></template>
<style scoped>
.overview-notices{grid-column:3 / -1;align-self:stretch;background:linear-gradient(135deg,#fff,#f4fbf9)}
.attention-list{display:grid;gap:10px}.attention-list a{display:flex;align-items:center;gap:14px;padding:16px;border:1px solid #deede8;border-radius:12px;background:white;color:#21495c;text-decoration:none;transition:background .18s,box-shadow .18s,transform .18s}
.attention-list a:hover{background:#edf9f5;box-shadow:0 5px 14px #187f7b20;transform:translateY(-2px)}.attention-list a:focus-visible{outline:3px solid #27ad9f;outline-offset:2px}.attention-list a>span{flex:1;min-width:0}.attention-list b{display:block;font-size:13px}.attention-list small{display:block;font-size:11px;margin-top:5px;color:#718a93}.attention-list em{font-size:11px;font-style:normal;color:#07897e}.attention-list :deep(.admin-png-icon){width:34px;height:34px}
@media(max-width:1250px){.overview-notices{grid-column:1 / -1}}@media(max-width:700px){.attention-list a{flex-wrap:wrap}.attention-list em{margin-left:48px}.overview-notices{grid-column:auto}}@media(prefers-reduced-motion:reduce){.attention-list a{transition:none}.attention-list a:hover{transform:none}}
</style>
