<script setup lang="ts">
import { ref, watch, onBeforeUnmount } from 'vue'
type Patient={id:number;full_name:string;nik:string;medical_record_number:string|null;phone:string;birth_date:string;gender:string;full_address:string;rt:string;rw:string;cadre?:{full_name:string};treatment_place_id:number}
const emit=defineEmits<{select:[patient:Patient|null]}>()
const query=ref(''),items=ref<Patient[]>([]),selected=ref<Patient|null>(null),loading=ref(false),error=ref(''),searched=ref(false),total=ref(0)
let timer:ReturnType<typeof setTimeout>|undefined, controller:AbortController|undefined, generation=0
watch(query,()=>{clearTimeout(timer);controller?.abort();const version=++generation;selected.value=null;emit('select',null);items.value=[];searched.value=false;error.value='';loading.value=false;if(query.value.trim().length<2)return;loading.value=true;timer=setTimeout(()=>search(version),300)})
async function search(version:number){controller=new AbortController();try{const r=await fetch('/api/v1/patients?status=active&per_page=20&search='+encodeURIComponent(query.value.trim()),{signal:controller.signal,headers:{Authorization:'Bearer '+sessionStorage.getItem('tb_token'),Accept:'application/json'}});const p=await r.json();if(version!==generation)return;if(!r.ok)throw new Error(p.message||'Gagal mencari pasien.');items.value=p.data;total.value=p.meta.total;searched.value=true}catch(e){if(version===generation && !(e instanceof DOMException && e.name==='AbortError'))error.value='Pencarian gagal. Ubah kata pencarian untuk mencoba lagi.'}finally{if(version===generation)loading.value=false}}
function choose(patient:Patient){selected.value=patient;emit('select',patient);items.value=[];searched.value=false}
function clear(){selected.value=null;emit('select',null);query.value=''}
onBeforeUnmount(()=>{clearTimeout(timer);controller?.abort();generation++})
</script>
<template><section class="patient-picker"><label for="patient-search">Cari pasien aktif</label><input id="patient-search" v-model="query" type="search" autocomplete="off" placeholder="Ketik nama, NIK, no. rekam medis, atau HP…" aria-describedby="patient-search-help"/><small id="patient-search-help">Ketik minimal 2 karakter, lalu pilih pasien dari hasil pencarian. Cocokkan identitas sebelum menyimpan.</small><p v-if="loading" role="status">Mencari pasien…</p><p v-if="error" role="alert">{{error}}</p><div v-if="items.length" class="patient-results" aria-label="Hasil pencarian pasien"><button v-for="patient in items" :key="patient.id" type="button" @click="choose(patient)"><b>{{patient.full_name}}</b><span>NIK: {{patient.nik}} · No. RM: {{patient.medical_record_number||'Belum tersedia'}}</span><span>HP: {{patient.phone}} · Lahir: {{new Date(patient.birth_date).toLocaleDateString('id-ID')}}</span></button></div><p v-if="searched && !items.length" role="status">Tidak ada pasien aktif yang cocok.</p><small v-if="searched && total>items.length">Menampilkan {{items.length}} dari {{total}} hasil. Perjelas nama atau gunakan NIK lengkap.</small><section v-if="selected" class="patient-preview" aria-label="Preview pasien terpilih" aria-live="polite"><div class="preview-heading"><div><small>Pasien terpilih • Aktif</small><h2>{{selected.full_name}}</h2></div><button type="button" @click="clear">Ganti pasien</button></div><dl><div><dt>NIK</dt><dd>{{selected.nik}}</dd></div><div><dt>No. rekam medis</dt><dd>{{selected.medical_record_number||'Belum tersedia'}}</dd></div><div><dt>Tanggal lahir / Jenis kelamin</dt><dd>{{new Date(selected.birth_date).toLocaleDateString('id-ID')}} / {{selected.gender==='L'?'Laki-laki':'Perempuan'}}</dd></div><div><dt>Nomor HP</dt><dd>{{selected.phone}}</dd></div><div><dt>Alamat</dt><dd>{{selected.full_address}} · RT {{selected.rt}} / RW {{selected.rw}}</dd></div><div><dt>Kader PMO</dt><dd>{{selected.cadre?.full_name||'Belum ditetapkan'}}</dd></div></dl></section></section></template>
<style scoped>
.patient-picker{min-width:0}.patient-picker>input{display:block;width:100%;box-sizing:border-box;margin-top:8px;padding:13px 15px;border:1px solid #c9e0dc;border-radius:10px;background:#fff;color:#204c59;font:14px Arial;min-height:46px}.patient-picker>input:focus{outline:3px solid #bcebe1;outline-offset:1px;border-color:#0d9b8e}.patient-picker>label{font-size:13px;font-weight:bold}.patient-picker>small{display:block;font-size:12px;font-weight:normal;line-height:1.6;color:#65858a;margin-top:6px}.patient-picker>p{font-size:12px}.patient-results{max-height:300px;overflow:auto;border:1px solid #cde6df;border-radius:10px;margin-top:10px}.patient-results button{display:block;width:100%;text-align:left;padding:14px;background:white;color:#204c59;border:0;border-bottom:1px solid #e3efeb;cursor:pointer}.patient-results button:hover,.patient-results button:focus-visible{background:#e5f7f2;outline:2px solid #159b8d;outline-offset:-2px}.patient-results span{display:block;font:12px/1.6 Arial;color:#65818c}.patient-preview{margin-top:16px;padding:20px;border:1px solid #bde2d8;background:linear-gradient(115deg,#edf9f4,#f6fcff);border-radius:12px}.preview-heading{display:flex;justify-content:space-between;gap:12px;align-items:center}.preview-heading h2{margin:4px 0;font-size:18px}.preview-heading small{color:#078277}.preview-heading button{background:white;color:#087e72;border:1px solid #bfdfd6;border-radius:8px;padding:9px;cursor:pointer}.patient-preview dl{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin:16px 0 0}.patient-preview dt{font-size:11px;color:#64868a}.patient-preview dd{margin:4px 0 0;font-size:13px;overflow-wrap:anywhere}@media(max-width:700px){.patient-preview dl{grid-template-columns:1fr}.preview-heading{align-items:flex-start}}
</style>
